name: 📊 Tests

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ./services_tools/.[test]

      - name: Run Pytest with coverage
        run: |
          pytest --cov=lite_media_core --cov-report=term ./service_tools/tests
          cp .coverage .coverage.regular
